if(document.querySelector(".comment-barrage")){var commentBarrageConfig={maxBarrage:GLOBAL_CONFIG.commentBarrageConfig.maxBarrage,barrageTime:GLOBAL_CONFIG.commentBarrageConfig.barrageTime,twikooUrl:GLOBAL_CONFIG.twikooEnvId,accessToken:GLOBAL_CONFIG.commentBarrageConfig.accessToken,mailMd5:GLOBAL_CONFIG.commentBarrageConfig.mailMd5,pageUrl:window.location.pathname,barrageTimer:[],barrageList:[],barrageIndex:0,dom:document.querySelector(".comment-barrage")},commentInterval=null,hoverOnCommentBarrage=!1;function initCommentBarrage(){var e,r;commentBarrageConfig.dom&&(e=JSON.stringify({event:"COMMENT_GET","commentBarrageConfig.accessToken":commentBarrageConfig.accessToken,url:commentBarrageConfig.pageUrl}),(r=new XMLHttpRequest).withCredentials=!0,r.addEventListener("readystatechange",function(){4===this.readyState&&this.responseText&&(commentBarrageConfig.barrageList=commentLinkFilter(JSON.parse(this.responseText).data),commentBarrageConfig.dom.innerHTML="")}),r.open("POST",commentBarrageConfig.twikooUrl),r.setRequestHeader("Content-Type","application/json"),r.send(e),clearInterval(commentInterval),commentInterval=null,commentInterval=setInterval(()=>{commentBarrageConfig.barrageList.length&&!hoverOnCommentBarrage&&(popCommentBarrage(commentBarrageConfig.barrageList[commentBarrageConfig.barrageIndex]),commentBarrageConfig.barrageIndex+=1,commentBarrageConfig.barrageIndex%=commentBarrageConfig.barrageList.length),commentBarrageConfig.barrageTimer.length>(commentBarrageConfig.barrageList.length>commentBarrageConfig.maxBarrage?commentBarrageConfig.maxBarrage:commentBarrageConfig.barrageList.length)&&!hoverOnCommentBarrage&&removeCommentBarrage(commentBarrageConfig.barrageTimer.shift())},commentBarrageConfig.barrageTime))}function commentLinkFilter(e){e.sort((e,r)=>e.created-r.created);let r=[];return e.forEach(e=>{r.push(...getCommentReplies(e))}),r}function getCommentReplies(e){if(e.replies){let r=[e];return e.replies.forEach(e=>{r.push(...getCommentReplies(e))}),r}return[]}function popCommentBarrage(e){var r=document.createElement("div");r.className="comment-barrage-item",r.innerHTML=`
          <div class="barrageHead">
            <a class="barrageTitle ${e.mailMd5===commentBarrageConfig.mailMd5?"barrageBloggerTitle":""}" href="javascript:chyt.scrollTo('#post-comment')"">
              ${e.mailMd5===commentBarrageConfig.mailMd5?"博主":"热评"}
            </a>
            <div class="barrageNick">${e.nick}</div>
            <img class="nolazyload barrageAvatar" src="https://cravatar.cn/avatar/${e.mailMd5}"/>
            <a class="comment-barrage-close" href="javascript:chyt.switchCommentBarrage()"><i class="chytfont chyt-icon-xmark"></i></a>
          </div>
          <chyt class="barrageContent" onClick="window.location.hash = '${e.id}'">
            ${e.comment}
          </chyt>
        `,r.querySelectorAll("chyt pre").forEach(e=>{var r=document.createElement("span");r.innerText="【代码】",e.parentNode.replaceChild(r,e)}),r.querySelectorAll("chyt img").forEach(e=>{var r;e.classList.contains("tk-owo-emotion")||(e.style.display="none",(r=document.createElement("span")).innerText="【图片】",e.parentNode.replaceChild(r,e))}),commentBarrageConfig.barrageTimer.push(r),commentBarrageConfig.dom.append(r)}function removeCommentBarrage(e){e.className="comment-barrage-item out",setTimeout(()=>{commentBarrageConfig.dom&&commentBarrageConfig.dom.contains(e)&&commentBarrageConfig.dom.removeChild(e)},1e3)}document.querySelector(".comment-barrage").addEventListener("mouseenter",function(){hoverOnCommentBarrage=!0}),document.querySelector(".comment-barrage").addEventListener("mouseleave",function(){hoverOnCommentBarrage=!1});let e=e=>{let r=document.querySelector(".comment-barrage"),a=document.getElementById("post-comment");e.forEach(e=>{a&&r&&768<document.body.clientWidth&&(r.style.bottom=e.isIntersecting?`-${200*commentBarrageConfig.maxBarrage}px`:"0")})},r=new IntersectionObserver(e,{root:null,rootMargin:"0px",threshold:0}),a=document.getElementById("post-comment");a&&r.observe(a),initCommentBarrage(),"false"!==localStorage.getItem("commentBarrageSwitch")?(document.querySelector(".comment-barrage").style.display="flex",document.querySelector(".menu-commentBarrage-text").textContent="关闭热评"):(document.querySelector(".comment-barrage").style.display="none",document.querySelector(".menu-commentBarrage-text").textContent="显示热评"),document.addEventListener("pjax:send",function(){clearInterval(commentInterval)})}